export const serviceApplicationVersion = 'service-application-v4';

export const serviceApplicationOptions = [
  {
    id: 'consulting',
    label: '專案卡關諮詢',
    shortLabel: '60 分鐘付費諮詢',
    summary: '手上已有具體問題，需要一起診斷、取捨並決定下一步。',
    offerNote: '14 天內加入陪跑，NT$5,000 諮詢費可以全額折抵。',
    situationLabel: '你現在最想解決哪件事？目前卡在哪裡？',
    situationHelp: '簡單交代情境和卡點即可，不需要先整理成完整企劃書。',
    focusQuestion: '這 60 分鐘，你最需要帶走什麼？',
    responseNote: '適合的話，我會回覆付款方式與可選時間；諮詢為 60 分鐘，費用 NT$5,000。',
    applicationCopy: {
      heroLabel: '60 分鐘付費諮詢',
      heroTitle: '先把你卡住的專案說清楚。',
      heroDescription: '告訴我你已經做過什麼、哪裡反覆出問題，以及這次最需要做哪個決定。我會先看這題適不適合用一次諮詢處理。',
      nextTitle: '我收到後會怎麼做',
      nextFirstStep: '先看問題與現有資料夠不夠。',
      formLabel: '',
      formTitle: '留下問題和聯絡方式。',
      formDescription: '留下名字或常用帳號名稱、Email，再回答兩個問題就好；其他資料有的話再補。',
      submitLabel: '送出付費諮詢申請',
      submitNote: '送出不會扣款或保留時段。適合的話，我會回覆 NT$5,000 付款方式與可選時間。',
    },
    focusOptions: [
      { id: 'find_root_cause', label: '找出真正卡點', summary: '現在看到的是症狀，還不確定問題到底出在哪。' },
      { id: 'compare_options', label: '比較方向、做取捨', summary: '手上有幾種做法，需要判斷哪一條比較值得走。' },
      { id: 'set_next_step', label: '決定先做什麼', summary: '事情很多，希望排出優先順序和下一步。' },
      { id: 'review_current_plan', label: '檢查目前做法', summary: '已經有方案或原型，想確認問題與風險。' },
    ],
  },
  {
    id: 'coaching',
    label: 'AI 應用陪跑',
    shortLabel: '申請五週一對一陪跑',
    summary: '我會先看你想做的事，再邀請適合的人免費聊 30 分鐘。',
    offerNote: '談完確認合作，會收到本期專屬優惠；做過 NT$5,000 專案諮詢者，14 天內加入仍可全額折抵。',
    situationLabel: '你最想把什麼做下去？現在做到哪裡？如果這五週有進展，你最希望看到什麼？',
    situationHelp: '工作、事業、產品或內容都可以，簡單寫目前進度和你希望出現的變化。',
    situationPlaceholder: '寫你想做什麼、目前手上有什麼，以及五週後最希望看到的進展。',
    focusQuestion: '你目前手上已經有什麼？',
    responseNote: '如果這次陪跑適合，我會回覆 30 分鐘免費聊聊的可選時間。',
    applicationCopy: {
      heroLabel: '五週一對一陪跑申請',
      heroTitle: '先讓我看看，我們適不適合一起做。',
      heroDescription: '簡單告訴我你想完成甚麼、目前做到哪裡。我會親自看，再邀請適合的人免費聊 30 分鐘。',
      nextTitle: '我收到後會怎麼做',
      nextFirstStep: '先看你正在做什麼、目前卡在哪裡。',
      formLabel: '',
      formTitle: '讓我先認識你正在做的事。',
      formDescription: '留下名字或常用帳號名稱、Email，再回答兩個簡單問題就好；其他資料有需要再補。',
      submitLabel: '送出陪跑申請',
      submitNote: '送出後不會扣款。我看過內容後，會再邀請適合的人聊 30 分鐘；談完確認合作，才會收到正式方案與專屬優惠。',
    },
    focusOptions: [
      { id: 'active_work_in_progress', label: '已經有正在做的東西', summary: '有內容、產品、流程或其他成果，可以直接一起看。' },
      { id: 'clear_direction_no_first_version', label: '有明確方向和素材', summary: '知道想做什麼，但還沒整理出第一版。' },
      { id: 'multiple_directions_need_priority', label: '手上有幾個方向', summary: '還不知道現在該先做哪一個。' },
      { id: 'early_idea_needs_clarity', label: '現在還只有模糊想法', summary: '想先把問題和方向說清楚。' },
    ],
  },
  {
    id: 'enterprise',
    label: '企業合作',
    shortLabel: '企業合作',
    summary: '從團隊現在的工作出發，再決定要做診斷、工作坊或小規模導入。',
    offerNote: '',
    situationLabel: '團隊現在最想改善哪件事？目前遇到什麼阻力？',
    situationHelp: '先說明使用情境、參與對象和目前做法；不需要先決定課程或導入形式。',
    focusQuestion: '這次最想先談哪一類合作？',
    responseNote: '我會先確認需求與適配，再決定是否安排進一步會議。',
    applicationCopy: {
      heroLabel: '企業合作',
      heroTitle: '先讓我看懂，團隊現在最想改善哪件事。',
      heroDescription: '告訴我誰正在做、目前怎麼做，以及最麻煩的是哪一段。不用先決定要上課、改流程或做系統。',
      nextTitle: '我收到後會怎麼做',
      nextFirstStep: '先看問題、參與對象與現有條件。',
      formLabel: '',
      formTitle: '先留下足以判斷的資訊。',
      formDescription: '只有聯絡方式和兩個問題；其他條件有的話再補。',
      submitLabel: '送出企業合作需求',
      submitNote: '送出不代表方案、價格或檔期已成立。我會先確認需求，再回覆是否適合往下談。',
    },
    focusOptions: [
      { id: 'team_diagnosis', label: '團隊使用診斷', summary: '先看目前怎麼使用 AI、問題在哪，再決定做法。' },
      { id: 'training_workshop', label: '內訓或工作坊', summary: '需要依真實工作情境設計培訓。' },
      { id: 'pilot_implementation', label: '小規模導入', summary: '想挑一個場景先做、驗證後再擴大。' },
      { id: 'not_sure_yet', label: '還不確定', summary: '先把問題和限制談清楚，再決定合作形式。' },
    ],
  },
  {
    id: 'partnerships',
    label: '講師與內容合作',
    shortLabel: '講師與內容',
    summary: '演講、工作坊、內容共創與產品合作邀約。',
    offerNote: '',
    situationLabel: '這次想合作什麼？目前已有什麼想法或條件？',
    situationHelp: '簡單說明主題、對象、形式與已知條件即可。',
    focusQuestion: '這次合作比較接近哪一種？',
    responseNote: '我會先確認主題、形式與檔期，再回覆是否適合往下談。',
    applicationCopy: {
      heroLabel: '講師與內容合作',
      heroTitle: '先把這次合作的基本條件說清楚。',
      heroDescription: '告訴我受眾、形式、日期與目前已知條件。我會先確認主題和檔期，再回覆是否適合。',
      nextTitle: '我收到後會怎麼做',
      nextFirstStep: '先看主題、形式與已知條件。',
      formLabel: '',
      formTitle: '留下這次邀約的基本資訊。',
      formDescription: '只有聯絡方式和兩個問題；日期、預算或連結有的話再補。',
      submitLabel: '送出合作邀約',
      submitNote: '送出不代表檔期或合作已成立。我確認過主題與條件後，會直接回覆是否適合。',
    },
    focusOptions: [
      { id: 'speaking', label: '演講或分享', summary: '單次主題演講、論壇或公開活動。' },
      { id: 'workshop', label: '工作坊', summary: '需要參與者動手做、帶走具體成果。' },
      { id: 'content', label: '內容共創', summary: '文章、影音、專題或其他內容合作。' },
      { id: 'product', label: '產品或其他合作', summary: '工具、平台、課程或其他形式。' },
    ],
  },
] as const;

export type ServiceApplicationId = typeof serviceApplicationOptions[number]['id'];

export function getServiceApplicationHref(service: ServiceApplicationId, source: string) {
  const params = new URLSearchParams({ service, source });
  return `/services/apply/?${params.toString()}`;
}
